<a href="https://colab.research.google.com/github/PriyathamVarma/PriyathamVarma/blob/main/IDAstar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import timeit
import numpy as np

def IDA(initial_state, goal_state):
    initial_node = Node(initial_state)
    goal_node = Node(goal_state)
    
    threshold = manhattan_heuristic(initial_state, goal_state)
    
    #print("heuristic threshold: {}".format(threshold))
    
    loop_counter = 0

    while 1:
        path = set([initial_node])
        
        tmp = search(initial_node, goal_state, 0, threshold, path)
        
        #print("tmp: {}".format(tmp))
        if tmp == True:
            return True, threshold
        elif tmp == float('inf'):
            return False, float('inf')
        else:
            threshold = tmp


def search(node, goal_state, g, threshold, path):
    #print("node-state: {}".format(node.state))
    f = g + manhattan_heuristic(node.state, goal_state)

    if f > threshold:
        return f

    if np.array_equal(node.state, goal_state):
        return True

    minimum = float('inf')  
    for n in node.nextnodes():
        if n not in path:
            path.add(n)
            tmp = search(n, goal_state, g + 1, threshold, path)
            if tmp == True:
                return True
            if tmp < minimum:
                minimum = tmp

    return minimum


def manhattan_heuristic(state1, state2):
    size = range(1, len(state1) ** 2)
    distances = [count_distance(num, state1, state2) for num in size]

    return sum(distances)


def count_distance(number, state1, state2):
    position1 = np.where(state1 == number)
    position2 = np.where(state2 == number)

    return manhattan_distance(position1, position2)


def manhattan_distance(a, b):
    return abs(b[0] - a[0]) + abs(b[1] - a[1])


class Node():
    def __init__(self, state):
        self.state = state
    
    def __repr__(self):
        return np.array_str(self.state.flatten())

    def __hash__(self):
        return hash(self.__repr__())
        
    def __eq__(self, other):
        return self.__hash__() == other.__hash__()

    def nextnodes(self):
        zero = np.where(self.state == 0)
        
        y,x = zero
        y = int(y)
        x = int(x)
        
        up = (y - 1, x) 
        down = (y + 1, x)
        right = (y, x + 1)
        left = (y, x - 1)

        arr = []
        for direction in (up, down, right, left):
            if len(self.state) - 1 >= direction[0] >= 0 and len(self.state) - 1 >= direction[1] >= 0:
                tmp = np.copy(self.state)
                tmp[direction[0], direction[1]], tmp[zero] = tmp[zero], tmp[direction[0], direction[1]]
                arr.append(Node(tmp))

        return arr

initialStates = [[0, 0, [[0, 7, 1], [4, 3, 2], [8, 6, 5]]],
[0, 2, [[5, 6, 0], [1, 3, 8], [4, 7, 2]]],
[2, 0, [[3, 5, 6], [1, 2, 7], [0, 8, 4]]],
[1, 1, [[7, 3, 5], [4, 0, 2], [8, 1, 6]]],
[2, 0, [[6, 4, 8], [7, 1, 3], [0, 2, 5]]] ]

finalState = np.array([[1,2,3],[4,5,6],[7,8,0]])
goalState = [0, 2, [[3, 2, 0], [6, 1, 8], [4, 7, 5]]]
print("ITERATIVE DEEPENING A STAR")
print("***********************")
print("GOAL STATE:",goalState)
print("***********************")

for k in initialStates:
  initialState = np.array( k[2] )
  # Time
  start = timeit.default_timer()
  is_found, th = IDA(initialState, finalState)
  stop = timeit.default_timer()

  # Reshaping the array
  reshape = initialState.reshape(3,3)


  print("RESULTS FOR:")
  print("[",k[0],",",k[1],",")
  print(reshape,"]")


  print('THE COMPUTING TIME THE SEARCH TOOK: {}'.format(stop - start))

  if is_found is True:
      print("NUMBER OF MOVES TO SOLVE: {}".format(th))
      print("--------------------------------------------")
  else:
      print("NOT POSSIBLE!")

ITERATIVE DEEPENING A STAR
***********************
GOAL STATE: [0, 2, [[3, 2, 0], [6, 1, 8], [4, 7, 5]]]
***********************
RESULTS FOR:
[ 0 , 0 ,
[[0 7 1]
 [4 3 2]
 [8 6 5]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.05297030099995936
NUMBER OF MOVES TO SOLVE: [16]
--------------------------------------------
RESULTS FOR:
[ 0 , 2 ,
[[5 6 0]
 [1 3 8]
 [4 7 2]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.16736110600004395
NUMBER OF MOVES TO SOLVE: [18]
--------------------------------------------
RESULTS FOR:
[ 2 , 0 ,
[[3 5 6]
 [1 2 7]
 [0 8 4]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.14896648400008417
NUMBER OF MOVES TO SOLVE: [20]
--------------------------------------------
RESULTS FOR:
[ 1 , 1 ,
[[7 3 5]
 [4 0 2]
 [8 1 6]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.20059671200010598
NUMBER OF MOVES TO SOLVE: [18]
--------------------------------------------
RESULTS FOR:
[ 2 , 0 ,
[[6 4 8]
 [7 1 3]
 [0 2 5]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.09512021699993056
NUMBER OF MOVES TO SOL

In [ ]:
ITERATIVE DEEPENING A STAR
***********************
GOAL STATE: [0, 2, [[3, 2, 0], [6, 1, 8], [4, 7, 5]]]
***********************
RESULTS FOR:
[ 0 , 0 ,
[[0 7 1]
 [4 3 2]
 [8 6 5]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.05297030099995936
NUMBER OF MOVES TO SOLVE: [16]
--------------------------------------------
RESULTS FOR:
[ 0 , 2 ,
[[5 6 0]
 [1 3 8]
 [4 7 2]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.16736110600004395
NUMBER OF MOVES TO SOLVE: [18]
--------------------------------------------
RESULTS FOR:
[ 2 , 0 ,
[[3 5 6]
 [1 2 7]
 [0 8 4]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.14896648400008417
NUMBER OF MOVES TO SOLVE: [20]
--------------------------------------------
RESULTS FOR:
[ 1 , 1 ,
[[7 3 5]
 [4 0 2]
 [8 1 6]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.20059671200010598
NUMBER OF MOVES TO SOLVE: [18]
--------------------------------------------
RESULTS FOR:
[ 2 , 0 ,
[[6 4 8]
 [7 1 3]
 [0 2 5]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.09512021699993056
NUMBER OF MOVES TO SOLVE: [20]
--------------------------------------------


In [ ]:
ITERATIVE DEEPENING A STAR
***********************
GOAL STATE: [2, 2, [[1, 2, 3], [4, 5, 6], [7, 8, 0]]]
***********************
RESULTS FOR:
[ 0 , 0 ,
[[0 1 8]
 [3 6 7]
 [5 4 2]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.06019220000007408
NUMBER OF MOVES TO SOLVE: [20]
--------------------------------------------
RESULTS FOR:
[ 2 , 0 ,
[[6 4 1]
 [7 3 2]
 [0 5 8]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.016171081000038612
NUMBER OF MOVES TO SOLVE: [14]
--------------------------------------------
RESULTS FOR:
[ 0 , 0 ,
[[0 7 1]
 [5 4 8]
 [6 2 3]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.8432354059998488
NUMBER OF MOVES TO SOLVE: [26]
--------------------------------------------
RESULTS FOR:
[ 0 , 2 ,
[[5 4 0]
 [2 3 1]
 [8 7 6]] ]
THE COMPUTING TIME THE SEARCH TOOK: 0.5621984130000328
NUMBER OF MOVES TO SOLVE: [22]
--------------------------------------------
RESULTS FOR:
[ 2 , 1 ,
[[8 6 7]
 [2 5 4]
 [3 0 1]] ]
THE COMPUTING TIME THE SEARCH TOOK: 3.1613714249999703
NUMBER OF MOVES TO SOLVE: [31]
--------------------------------------------